version: '3.8'

services:
  # MongoDB Database  
  mongo:
    build:
      context: ./mongo/database
      dockerfile: Dockerfile
    container_name: mern_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: appdb
    volumes:
      - mongodb_data:/data/db
    networks:
      - mern_network

  # Backend API
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: mern_backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGO_URI: mongodb://mongo:27017/appdb?authSource=admin
    depends_on:
      - mongo
    networks:
      - mern_network

  # Frontend
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: mern_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - mern_network

volumes:
  mongodb_data:

networks:
  mern_network:
    driver: bridge