apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-config
  namespace: mern-app
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      root /usr/share/nginx/html;
      index index.html;

      location /assets/ {
        try_files $uri =404;
      }

      location /healthz {
        return 200 'ok';
        add_header Content-Type text/plain;
      }

      location / {
        try_files $uri /index.html;
      }
    }
