apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-config
data:
  nginx.conf: |
    events {}
    http {
      upstream frontend { server frontend-service:80; }
      upstream backend  { server backend-service:3000; }
      upstream mongo_ui { server mongo-express-service:8081; }

      server {
        listen 443 ssl;
        ssl_certificate     /etc/nginx/certs/tls.crt;
        ssl_certificate_key /etc/nginx/certs/tls.key;
        location /     { proxy_pass http://frontend; }
        location /api/ { proxy_pass http://backend; }
        location /db/  { proxy_pass http://mongo_ui; }
      }
    }
