# k8s/secret-mongo.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongo-auth
  namespace: mern
type: Opaque
stringData:
  username: admin
  password: admin123

---
apiVersion: v1
kind: Secret
metadata:
  name: me-basic-auth
  namespace: mern
type: Opaque
stringData:
  user: admin
  pass: admin123
